config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from subjects.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('groups/', include('groups.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
from . import views

app_name = 'teachers'

urlpatterns = [
    path('list/', views.teacher_list, name='list'),
    path('create/', views.teacher_create, name='create'),
    path('detail/<int:pk>/', views.teacher_detail, name='detail'),
    path('update/<int:pk>/', views.teacher_update, name='update'),
    path('delete/<int:pk>/', views.teacher_delete, name='delete'),
]

teachers/models.py
from django.db import models
from django.shortcuts import reverse

from subjects.base_models import BaseModel
from subjects.models import Subject


class Teacher(BaseModel):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    teacher_phone = models.CharField(max_length=15)
    teacher_email = models.EmailField(max_length=100, unique=True)
    work_experience = models.PositiveIntegerField()
    image = models.ImageField(upload_to='teachers/')
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True, related_name='teachers')


    def __str__(self):
        return f"{self.first_name} {self.last_name}"


    def get_detail_url(self):
        return reverse('teachers:detail', args=[self.pk])

    def get_delete_url(self):
        return reverse('teachers:delete', args=[self.pk])

    def get_update_url(self):
        return reverse('teachers:update', args=[self.pk])

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from subjects.models import Subject
from .models import Teacher


def teacher_list(request):
    teachers = Teacher.objects.all()
    ctx = {'teachers': teachers}
    return render(request, 'teachers/teachers-list.html', ctx)

def teacher_create(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        teacher_phone = request.POST.get('teacher_phone')
        subject_id = request.POST.get('subject')
        teacher_email = request.POST.get('teacher_email')
        work_experience = request.POST.get('work_experience')
        image = request.FILES.get('image')
        print(first_name, last_name, teacher_email, teacher_phone, subject_id, work_experience, image)
        if first_name and last_name and teacher_phone and subject_id and teacher_email and work_experience and image:
            subject = Subject.objects.get(pk=subject_id)
            Teacher.objects.create(
                first_name=first_name,
                last_name=last_name,
                subject=subject,
                teacher_phone=teacher_phone,
                teacher_email= teacher_email,
                work_experience=work_experience,
                image=image,
            )
            return redirect('teachers:list')
    subjects = Subject.objects.all()
    ctx = {'subjects': subjects}
    return render(request, 'teachers/teacher-form.html', ctx)

def teacher_detail(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    ctx = {'teacher': teacher}
    return render(request, 'teachers/teacher-detail.html', ctx)

def teacher_delete(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    if request.method == 'POST':
        teacher.delete()
        return redirect('teachers:list')
    ctx = { 'teacher': teacher }
    return render(request, 'teachers/teacher-delete-confirm.html', ctx)


def teacher_update(request, pk):
    teacher = get_object_or_404(Teacher, pk=pk)
    subjects = Subject.objects.all()
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        teacher_phone = request.POST.get('teacher_phone')
        subject_id = request.POST.get('subject')
        teacher_email = request.POST.get('teacher_email')
        work_experience = request.POST.get('work_experience')
        image = request.FILES.get('image')

        if (first_name and last_name and teacher_phone and subject_id and
                teacher_email and work_experience):
            try:
                subject = Subject.objects.get(pk=subject_id)
                teacher.subject = subject
            except Subject.DoesNotExist:
                return redirect('teachers:update', pk=pk)
            teacher.first_name = first_name
            teacher.last_name = last_name
            teacher.teacher_phone = teacher_phone
            teacher.teacher_email = teacher_email
            teacher.work_experience = work_experience
            if image:
                teacher.image = image

            teacher.save()
            return redirect('teachers:detail', pk=teacher.pk)

    ctx = {'teacher': teacher, 'subjects': subjects,}
    return render(request, 'teachers/teacher-form.html', ctx)

templates/teachers/teacher-delete-confirm.html
{% extends 'base.html'%}

{% block title %}Maktab CRM - O'qituvchi o'chirish{% endblock %}

{% block content %}
<h1>O'qituvchi o'chirish</h1>
<p>O'qituchi <strong>{{ teacher.first_name }}{{ teacher.last_name }}</strong>o'chirilsinmi?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">O'chirish</button>
    <a href="{% url 'teachers:list' %}" class="btn btn-secondary">Bekor qilish</a>
</form>
{% endblock %}

templates/teachers/teacher-detail.html
{% extends 'base.html'%}

{% block title %}Maktab CRM - O'qituvchi ma'lumotlari{% endblock %}

{% block content %}
<h1>O'qituvchi ma'lumotlari</h1>
<div class="teacher-details">
    <div class="teacher-info">
        <!-- Static Teacher Image -->
        <img src="{{ teacher.image.url }}" alt="O'qituvchi rasmi" class="teacher-image">
        <h2>{{ teacher.first_name }} {{ teacher.last_name }}</h2>
        <p>ID: <span>{{ teacher.pk }}</span></p>
        <p>Fan: <span>{{ teacher.subject }}</span></p>
        <p>Telefon: <span>{{ teacher.teacher_phone }}</span></p>
        <p>Email: <span>{{ teacher.teacher_email }}</span></p>
        <p>Ish tajribasi: <span>{{ teacher.work_experience }}</span></p>
    </div>
</div>
<div class="actions">
    <a href="{{ teacher.get_update_url }}" class="btn"><i class="fas fa-edit"></i> Tahrirlash</a>
    <a href="{{ teacher.get_delete_url }}" class="btn btn-danger"><i class="fas fa-trash"></i> O'chirish</a>
</div>
{% endblock %}

templates/teachers/teacher-form.html
{% extends 'base.html'%}

{% block title %}Music Collection{% endblock %}

{% block content %}
<h1>{% if teacher %}O'qituvchi ma'lumotini tahrirlash{% else %}Yangi O'qituvchi yaratish{% endif %}</h1>
    <form  method="post" id="createTeacherForm" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">Ism:</label>
            <input type="text" id="first_name" name="first_name" placeholder="Ismingizni kiriting" value="{{ teacher.first_name }}" required>
        </div>
        <div class="form-group">
            <label for="last_name">Familiya:</label>
            <input type="text" id="last_name" name="last_name" placeholder="Familiyangizni kiriting" value="{{ teacher.last_name }}" required>
        </div>
        <div class="form-group">
            <label for="subject">Fan:</label>
            <select id="subject" name="subject" required>
                {% for subject in subjects %}
                    <option value="{{ subject.id }}">{% if teacher.subject.id == subject.id %}{% endif %}{{ subject.subject_name }}</option>
                {% empty %}
                    <option value="">Hozircha fanlar yo'q</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="teacher_phone">Telefon:</label>
            <input type="tel" id="teacher_phone" name="teacher_phone" placeholder="Telefon raqamingizni kiriting" value="{{ teacher.teacher_phone }}" required>
        </div>
        <div class="form-group">
            <label for="teacher_email">Email:</label>
            <input type="email" id="teacher_email" name="teacher_email" placeholder="Email manzilingizni kiriting" value="{{ teacher.teacher_email }}" required>
        </div>
        <div class="form-group">
            <label for="work_experience">Ish tajribasi (yil):</label>
            <input type="number" id="work_experience" name="work_experience" placeholder="Ish tajribangizni kiriting" value="{{ teacher.work_experience }}" required>
        </div>
        <div class="form-group">
            <label for="image">Rasm:</label>
            {% if teacher.image %}
                <img src="{{ teacher.image.url }}" alt="Current Image" class="teacher-image">
            {% endif %}
            <input type="file" id="image" name="image" accept="image/*">
        </div>
        <div class="actins">
            <button type="submit" class="btn">
                <i class="fas fa-save"></i>{% if teacher %}Tahrirlash{% else %}Saqlash{% endif %}
            </button>
            <a href="{% url 'teachers:list' %}" class="btn btn-secondary"><i class="fas fa-times"></i>Bekor qilish</a>
        </div>
    </form>
{% endblock %}

templates/teachers/teachers-list.html
{% extends 'base.html'%}

{% block title %}Maktab CRM - O'qituvchilar ro'yxati{% endblock %}

{% block content %}
<h1>O'qituvchilar ro'yxati</h1>
<div class="actions">
    <a href="{% url 'teachers:create' %}" class="btn"><i class="fas fa-plus"></i> Yangi o'qituvchi qo'shish</a>
    <input type="text" id="searchStudent" placeholder="O'qituvchi qidirish" class="search-input">
</div>
<table id="teachersTable">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ism</th>
            <th>Familiya</th>
            <th>Fan</th>
            <th>Amallar</th>
        </tr>
    </thead>
    <tbody>
    {% for teacher in teachers %}
        <tr>
            <td>{{ teacher.pk }}</td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.subjects }}</td>
            <td>
                <a href="{{ teacher.get_detail_url }}" class="btn btn-sm"><i class="fas fa-eye"></i> Ko'rish</a>
                <a href="{{ teacher.get_update_url }}" class="btn btn-sm"><i class="fas fa-edit"></i> Tahrirlash</a>
                <a href="{{ teacher.get_delete_url }}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i> O'chirish</a>
            </td>
        </tr>
    {% empty %}
        <td>Hozircha o'qituchilar yo'q</td>
    {% endfor %}
    </tbody>
</table>
<div class="pagination">
    <a href="#" class="btn btn-secondary"><i class="fas fa-chevron-left"></i> Oldingi</a>
    <span>1</span>
    <a href="#" class="btn btn-secondary">Keyingi <i class="fas fa-chevron-right"></i></a>
</div>
{% endblock %}